### ISSUE TITLE
Search more than 3 chunks

### ISSUE THREAD

**Issue by harrisonratcliffe** [WiIIiam278/SignSearch#11]
Hello, I need to find a single sign in a 200GB world. Is it possible to use this plugin/modify it to do that?

**Comment by WiIIiam278** [comment]
200GB?! Oh my goodness gracious me. I think your best choice would be tools that specially search signs in worlds - I forget the name of one but I recall FitMC mentioning it in a video one time. 
Even modifying this tool to search more chunks would be like trying to search for a pine cone in a power plant. I'd suggest researching tools like the one he mentioned that comb through sign NBT data from the world files directly.

**Comment by WiIIiam278** [comment]
Closing this for the aforementioned reason
